### ISSUE TITLE
프로젝트 설계

### ISSUE THREAD

**Issue by Xurhee** [22-1-OSS-Team-25/Project#1]
## 설계 요구사항

> CRUD(파일 I/O, 검색 기능 포함 10개 이상의 함수로 구현), 구조체 활용

---

과제에서 필요로 하는 설계 요구사항을 써봤습니다.

지금까지 진행해왔던 과제를 응용하는 것 같아서 큰 부담은 안가져도 될 것 같아요.

제 생각에 개발 순서는

> 주제 선정 > 구조체 멤버 정의 > CRUD 라이브러리 & 함수 정의 > CLI 인터페이스 설계 > 디버그 분기점 정의

순으로 나아가면 괜찮지 않을까 싶어요.

혹시 어떻게 생각하세요?

**Comment by 22100584** [comment]
너무 좋은 것 같아요!! 일단 주제는 무엇으로 할 지 빨리 정해보면 좋을 것 같아요!!!

**Comment by Xurhee** [comment]
알겠습니다! 따로 이슈 열어서 논의해 보도록 해요.
