### ISSUE TITLE
함수 구현하면서 상의해야할 것

### ISSUE THREAD

**Issue by 22100584** [22-1-OSS-Team-25/Project#14]
1. search함수에서 어떤 변수로 데이터를 찾아야할지..?
2. analyze함수에서 퍼센티지만 구현해도 되는지...?

**Comment by Xurhee** [comment]
1. 음 일단 날짜, 지출 금액 이 두가지가 가장 큰 것 같아요.
2. Analyze 함수에서는 퍼센트랑 해당 카테고리의 금액까진 보여주면 좋지 않을까요?

**Comment by 22100584** [comment]
1. 근데 날짜로 하면 printDate랑 너무 겹쳐서.. 그럼 지출 금액 예를 들어 10만원 이상 쓴 거만 search하는 것으로 찾을 까요?
2.  이미 그렇게 구현 했어요~~

**Comment by Xurhee** [comment]
알겠습니다~!
