### ISSUE TITLE
주제 선정 아이디어

### ISSUE THREAD

**Issue by 22100584** [22-1-OSS-Team-25/Project#2]
주제로 제가 생각한 거는 요즘 배달비가 점점 많이 오르다보니 한동대학생 뿐만 아니라 많은 분들이 부담을 갖고 있어요
그래서 특정 몇 명이 모일 지 정하고 어떤 메뉴를 할 지 정해서 올려놓으면 같이 주문해서 특정 장소에서 같이 받아가는 프로그램을 만들면 어떨까 싶어요... 그냥 아이디어니까 마구 던져보아요 ㅎㅎ

**Comment by Xurhee** [comment]
한 파일을 여러 사람이 공유해서 쓰는게 좋은 방식일진 잘 모르겠습니다..! 아니면 가계부 프로그램은 어떤가요?

**Comment by 22100584** [comment]
오 가계부 프로그램도 매우 좋은 것 같아요. 그 주제로 한 번 구현해보아요~
