### ISSUE TITLE
함수 설계

### ISSUE THREAD

**Issue by 22100584** [22-1-OSS-Team-25/Project#3]
CRUD 함수 정의와 기능을 구현해봅시다.

**Comment by Xurhee** [comment]
일단 CRUD를 포함해야 하니까, Create, Read, Update, Delete 이렇게 4개의 함수는 구현이 필요해요

**Comment by 22100584** [comment]
파일 입출력과 검색기능도 필요할 것 같아요.
Save, Load, Search 3개 함수도 필요해요

**Comment by Xurhee** [comment]
출력은 용도에 따라 다양하게 만드는게 어떨까요?

전체 가계부 데이터 출력과, 카테고리별, 날짜별 이런식으로 3개정도 따로 구현해 두면 좋지 않을까 합니다!

**Comment by 22100584** [comment]
소비형태를 경제지식을 참고해서 분석해주는 기능이 있으면 좋을 것 같아요.
예를 들어, 각 카테고리 별로 소비 퍼센티지를 계산하여서 다음 달에는 어떻게 쓰는 것이 좋을지 분석해주는 기능이요!

**Comment by Xurhee** [comment]
알겠습니다.

구조체 멤버도 같이 정해볼까요?

- 날짜
- 수입/지출 여부
- 금액
- 카테고리
- 메모

일단 이정도 생각이 드는데 어떻게 생각하세요?

**Comment by 22100584** [comment]
아주 좋아요!!!
