### ISSUE TITLE
프로젝트 이름 선정

### ISSUE THREAD

**Issue by Xurhee** [22-1-OSS-Team-25/Project#5]
개발이나 프로젝트랑은 크게 상관없지만, 프로그램의 이름을 정하는 것도 나쁘진 않을 것 같아요 ㅎㅎ

저희가 가계부 프로그램을 만드니까 **Ledger** 앞에 **You**를 의미하는 **U**를 붙여서 **_ULedger_** 이런식으로 제가 한번 지어봤는데 어떻게 생각하세요?

**Comment by 22100584** [comment]
좋은 거 같아요^^ 근데 U랑 leder?사이에 _이런 기호 붙이는 것 도 좋을것같아요

**Comment by Xurhee** [comment]
**U_Ledger** 이런식으로 말하신 것 맞으시죠?

**Comment by Xurhee** [comment]
제 개인적인 생각은 `_` 문자가 안붙은게 더 괜찮은것 같긴 합니다..!

**Comment by 22100584** [comment]
ULedger도 좋을것 깉아요 !!

**Comment by Xurhee** [comment]
알겠습니다!
